openapi: 3.0.3
info:
  title: h24s_10
  version: 0.0.1
  description: traP 24 spring hackathon team 10

paths:
  /events:
    summary: event
    description: event description
    post:
      description: create a new event
      tags:
        - event
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostEventRequest"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostEventResponse"
  /events/{eventID}:
    parameters:
      - $ref: "#/components/parameters/eventID"
    get:
      tags:
        - event
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetEventResponse"
  /events/{eventID}/participants:
    parameters:
      - $ref: "#/components/parameters/eventID"
    get:
      description: イベントの確定した参加者を取得
      tags:
        - event
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetEventParticipantsResponse"
  /events/{eventID}/targets:
    parameters:
      - $ref: "#/components/parameters/eventID"
    get:
      description: イベントの参加候補者を取得
      tags:
        - event
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetEventTargetsResponse"
  /events/{eventID}/applicants:
    parameters:
      - $ref: "#/components/parameters/eventID"
    post:
      description: 都合のいい日程候補を提出
      tags:
        - event
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostEventApplicantsRequest"
      responses:
        201:
          description: Created
    get:
      description: イベント参加希望を出した人たちを取得
      tags:
        - event
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetEventApplicantsResponse"
  /traq/groups:
    get:
      description: get all traQ groups
      tags:
        - traq
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetTraQGroupsResponse"
  /traq/users:
    get:
      description: get all traQ users
      tags:
        - traq
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetTraQUsersResponse"

components:
  schemas:
    PostEventRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        dateOptions:
          type: array
          items:
            type: object
            properties:
              start:
                type: string
                format: date-time
              end:
                type: string
                format: date-time
            required:
              - start
              - end
        targets:
          type: array
          items:
            type: string
            description: traQ ID
      required:
        - title
        - description
        - dateOptions
        - targets
    PostEventResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required:
        - id
    GetEventResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        isConfirmed:
          type: boolean
        date:
          type: object
          properties:
            start:
              type: string
              format: date-time
            end:
              type: string
              format: date-time
          required:
            - start
            - end
        dateOptions:
          type: array
          items:
            $ref: "#/components/schemas/dateOption"
      required:
        - event_id
        - title
        - description
        - status
    PostEventApplicantsRequest:
      type: object
      properties:
        dateOptionIDs:
          type: array
          items:
            type: string
            format: uuid
            description: 日時候補のID
    GetEventParticipantsResponse:
      type: array
      items:
        type: string
        description: traQ user ID
    GetEventTargetsResponse:
      type: array
      items:
        type: string
        description: traQ userID
    GetEventApplicantsResponse:
      type: array
      items:
        type: object
        properties:
          userID:
            type: string
          dateOptionIDs:
            type: array
            items:
              type: string
    GetTraQGroupsResponse:
      type: object
      properties:
        name:
          type: string
        members:
          type: array
          items:
            $ref: "#/components/schemas/traQUser"
    GetTraQUsersResponse:
      type: array
      items:
        $ref: "#/components/schemas/traQUser"
    dateOption:
      type: object
      properties:
        id:
          type: string
          format: uuid
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
      required:
        - id
        - start
        - end
    traQUser:
      type: object
      properties:
        name:
          type: string
        displayName:
          type: string
      required:
        - name
        - displayName

  parameters:
    eventID:
      name: eventID
      in: path
      required: true
      schema:
        type: string
        format: uuid
    groupName:
      name: groupName
      in: path
      required: true
      schema:
        type: string
